# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('fridays', 'Fridays'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10)),
                ('month', models.PositiveIntegerField(max_length=2)),
                ('year', models.PositiveIntegerField(max_length=4)),
                ('hour_from', models.DateField()),
                ('hour_to', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
